# Server configuration
server.port=8080
server.servlet.context-path=/initialize
spring.application.name=Initialize Java8 Project
#spring.profiles.active=dev

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db?rewriteBatchedStatements=true&currentSchema=test_schema
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.properties.hibernate.default_schema=test_schema
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.batch_versioned_data=true

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog/changelog-master.xml
spring.liquibase.parameters.liquibase.secureParsing=false


